"resource/ui/CreateServerPage.res"
{
	"CreateServerPanel"
	{
		"ControlName"	"CTFCreateMultiplayerGameServerPage"
		"fieldName"		"CreateServerPanel"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"		"46 43 42 255"
		"infocus_bgcolor_override"		"46 43 42 0"
		"outoffocus_bgcolor_override"	"46 43 42 0"
		"paintbackgroundtype"	"2"
		"paintborder"			"1"
		"paintbackground"		"1"
		"border"				"TFFatLineBorderOpaque"
	}

	"GamemodeList"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"GamemodeList"
		"xpos"				"c-350"
		"ypos"				"25"
		"wide"				"220"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"0"
		"unicode"			"0"
	}
	
	"ServerOptionsButton"
	{
		"ControlName"		"CExButton"
		"fieldName"			"ServerOptionsButton"
		"xpos"				"440"
		"ypos"				"26"
		"wide"				"185"
		"tall"				"26"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"0"
		"unicode"			"0"
		"labelText"			"Server Options"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"command"			"ServerOptions"
	}

	"MapLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapLabel"
		"font"			"HudFontMedium"
		"labelText"		"%maplabel%"
		"textAlignment"	"center"
		"xpos"			"c-470"
		"ypos"			"345"
		"zpos"			"4"
		"wide"			"480"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	"MapLabelShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapLabelShadow"
		"font"			"HudFontMedium"
		"labelText"		"%maplabel%"
		"textAlignment"	"center"
		"xpos"			"c-470"
		"ypos"			"347"
		"zpos"			"3"
		"wide"			"480"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"TransparentBlack"
	}
}