"Resource/UI/HudSecondaryAmmoWeapons.res"
{	
	"SecondaryAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"SecondaryAmmoBG"
		"xpos"			"5"
		"ypos"			"103"
		"zpos"			"0"
		"wide"			"84"
		"tall"			"42"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/misc_ammo_area_blue"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/misc_ammo_area_red"
		"teambg_2_lodef"	"../hud/misc_ammo_area_red_lodef"
		"teambg_3"		"../hud/misc_ammo_area_blue"
		"teambg_3_lodef"	"../hud/misc_ammo_area_blue_lodef"
	}
	
	"SecondaryAmmoValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SecondaryAmmoValue"
		"xpos"			"0"
		"ypos"			"112"
		"ypos_lodef"	"121"
		"zpos"			"2"
		"wide"			"84"
		"tall"			"26"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%SecondaryAmmo%"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"HudFontMedium"
		"font_lodef"	"HudFontMedium"
	}
	"SecondaryAmmoValue2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SecondaryAmmoValue"
		"fgcolor"		"Black"
		"xpos"			"1"
		"ypos"			"113"
		"zpos"			"2"
		"wide"			"84"
		"tall"			"26"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%SecondaryAmmo%"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"HudFontMedium"
		"font_lodef"	"HudFontMedium"
	}
}