"Resource/UI/HudSuitPower.res"
{
    "HudSuitPower" 
    {
        "ControlName"    "EditablePanel"
        "fieldName"      "HudSuitPower"
        "xpos"           "-8"
        "ypos"           "r150"
        "wide"           "150"
        "tall"           "60"
        "visible"        "1"
        "enabled"        "1"
    }
	"ItemEffectMeterLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterLabel"
		"xpos"					"15"
		"ypos"					"6"
		"zpos"					"2"
		"wide"					"75"
		"tall"					"50"
		"autoResize"			"0"
		"pinCorner"				"2"
		"visible"				"1"
		"visible_minmode"		"1"
		"ypos_minmode"			"0"
		"xpos_minmode"			"0"
		"textAlignment_minmode"			"west"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"SPRINT"
		"textAlignment"	        "Left"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"TFFontBold"
	}

	"SprintCharge"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"SprintCharge"
		"font"			"Default"
		"xpos"					"15"
		"ypos"					"38"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"6"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}																									
}
