"Resource/UI/winpanel.res"
{
	"TFStatsSummary"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"TFStatsSummary"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"
	}

	"MainBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MainBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleImage"		"1"
	}	

	"MapInfo"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"MapInfo"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
		"visible"	"0"
		"enabled"	"1"
		"bgcolor_override"	"46 43 42 255"
	
		"Background"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"Background"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"640"
			"tall"			"480"
			"visible"		"1"
			"enabled"		"1"
			"image"			"stamp_background_map"
			"scaleImage"		"1"
		}

		"MapImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MapImage"
			"xpos"			"30"
			"ypos"			"45"
			"zpos"			"2"
			"wide"			"300"
			"tall"			"300"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleImage"	"1"		
		}
	
		"ContributedLabel"
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"ContributedLabel"
			"xpos"			"30"
			"ypos"			"345"
			"zpos"			"40"
			"wide"			"300"
			"tall"			"100"
			"visible"		"0"
			"enabled"		"1"
	
			"BG"
			{
				"ControlName"	"EditablePanel"
				"fieldName"		"BG"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"300"
				"tall"			"55"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"border"		"TFThinLineBorder"
			}
	
			"ActualLabel"
			{
				"ControlName"		"CExLabel"
				"fieldName"		"ActualLabel"
				"font"			"HudFontSmallBold"
				"labelText"		"#TF_Contributed"
				"textAlignment"		"center"
				"xpos"			"10"
				"ypos"			"0"
				"zpos"			"40"
				"wide"			"280"
				"tall"			"55"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"centerwrap"	"1"
				"wrap"			"1"
			}					
		}
	
		"InfoBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"InfoBG"
			"xpos"			"c+10"
			"ypos"			"120"
			"wide"			"285"
			"tall"			"280"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"border"		"TFThinLineBorder"
		}

		"Title"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Title"
			"font"			"HudFontSmallBold"
			"labelText"		"%title%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"135"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "255 181 50 255"
		}
		"MapAuthors"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MapAuthors"
			"font"			"HudFontSmallBold"
			"labelText"		"%authors%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"155"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"275"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"0"
		}

		"MapLeaderboardTitle"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MapLeaderboardTitle"
			"font"			"HudFontSmallBold"
			"labelText"		"%map_leaderboard_title%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "137 191 60 255"
		}
	}

	"OnYourWayLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"OnYourWayLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#LoadingMap"
		"textAlignment"		"center"
		"xpos"			"c+10"
		"ypos"			"30"
		"zpos"			"40"
		"wide"			"285"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "173 168 148 255"
	}					
	"MapLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"MapLabel"
		"font"			"HudFontMediumBigBold"
		"labelText"		"%maplabel%"
		"textAlignment"		"center"
		"xpos"			"c-25"
		"ypos"			"55"
		"zpos"			"50"
		"wide"			"350"
		"tall"			"70"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"centerwrap"	"1"
	}
	"MapType"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapType"
		"font"			"HudFontSmallBold"
		"labelText"		"%maptype%"
		"textAlignment"	"center"
		"xpos"			"c-25"
		"ypos"			"115"
		"zpos"			"50"
		"wide"			"350"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}					
	"CampaignProgress"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"CampaignProgress"
		"xpos"		"300"
		"ypos"		"40"
		"zpos"		"1"
		"wide"		"560"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"
		
		"CampaignBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"CampaignBG"
			"xpos"			"c-315"
			"ypos"			"165"
			"wide"			"375"
			"tall"			"150"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"border"		"TFThinLineBorder"
		}
		
		"CampaignText"
		{
			"ControlName"		"Label"
			"fieldName"		"CampaignText"
			"font"			"ScoreboardMedium"
			"labelText"		"#Campaign_Label"
			"textAlignment"		"center"
			"xpos"			"c-280"
			"ypos"			"175"
			"wide"			"300"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		
		"CampaignInfoBG"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"CampaignInfoBG"
			"xpos"			"c-290"
			"ypos"			"230"
			"zpos"			"100"
			"wide"			"312"
			"tall"			"40"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"	
			"fillcolor"		"0 0 0 80"
			"PaintBackgroundType"	"0"
		}
	}	
	
	"CampaignPercent"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignPercent"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"%campaignpercent%%"
		"textAlignment"		"west"
		"xpos"			"c200"
		"ypos"			"c25"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"CampaignPercentLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignPercentLabel"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"Campaign Progress:"
		"textAlignment"		"west"
		"xpos"			"c25"
		"ypos"			"c25"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"CampaignMapCountLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignMapCountLabel"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"Map count:"
		"textAlignment"		"west"
		"xpos"			"c25"
		"ypos"			"c43"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"CampaignMapCount"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignMapCount"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"%mapindex%"
		"textAlignment"		"west"
		"xpos"			"c200"
		"ypos"			"c43"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"CampaignMapLabel2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignMapLabel2"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"/"
		"textAlignment"		"west"
		"xpos"			"c235"
		"ypos"			"c43"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	"CampaignMapCount2"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"CampaignMapCount2"
		"font"			"HudFontMediumSmallSecondary"
		"labelText"		"%lastmapindex%"
		"textAlignment"		"west"
		"xpos"			"c260"
		"ypos"			"c43"
		"zpos"			"50"
		"wide"			"500"
		"tall"			"35"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"StatData"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"StatData"
		"xpos"		"-75"
		"ypos"		"15"
		"zpos"		"1"
		"wide"		"500"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"
		"AveragesBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"AveragesBG"
			"xpos"			"c-295"
			"ypos"			"175"
			"wide"			"253"
			"tall"			"240"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"border"		"TFThinLineBorder"
		}
		"AveragesLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"AveragesLabel"
			"font"			"ScoreboardMedium"
			"labelText"		"#StatSummary_Label_PerformanceReport"
			"textAlignment"		"west"
			"textAlignment_hidef"		"center"
			"textAlignment_lodef"		"center"
			"xpos"			"c-285"
			"xpos_hidef"			"c-193"
			"xpos_lodef"			"c-193"
			"ypos"			"185"
			"wide"			"300"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}					
		"RecordsSubBG1"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"RecordsSubBG1"
			"xpos"			"c-280"
			"ypos"			"210"
			"ypos_hidef"			"229"
			"ypos_lodef"			"229"
			"zpos"			"2"
			"wide"			"215"
			"wide_hidef"			"540"
			"wide_lodef"			"540"
			"tall"			"190"
			"tall_hidef"			"183"
			"tall_lodef"			"183"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"	
			"fillcolor"		"0 0 0 80"
			"PaintBackgroundType"	"0"
		}
		"OverallRecord1Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord1Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord1label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"214"
			"ypos_hidef"			"246"
			"ypos_lodef"			"246"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord1Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord1Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord1value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"214"
			"ypos_hidef"			"246"
			"ypos_lodef"			"246"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord2Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord2label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"224"
			"ypos_hidef"			"258"
			"ypos_lodef"			"258"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord2Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord2value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"224"
			"ypos_hidef"			"258"
			"ypos_lodef"			"258"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord3Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord3label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"234"
			"ypos_hidef"			"270"
			"ypos_lodef"			"270"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord3Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord3value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"234"
			"ypos_hidef"			"270"
			"ypos_lodef"			"270"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord4Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord4label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"244"
			"ypos_hidef"			"282"
			"ypos_lodef"			"282"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord4Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord4value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"244"
			"ypos_hidef"			"282"
			"ypos_lodef"			"282"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord5Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord5label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"254"
			"ypos_hidef"			"294"
			"ypos_lodef"			"294"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord5Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord5value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"254"
			"ypos_hidef"			"294"
			"ypos_lodef"			"294"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord6Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord6label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"264"
			"ypos_hidef"			"306"
			"ypos_lodef"			"306"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord6Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord6value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"264"
			"ypos_hidef"			"306"
			"ypos_lodef"			"306"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord7Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord7label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"274"
			"ypos_hidef"			"318"
			"ypos_lodef"			"318"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord7Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord7value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"274"
			"ypos_hidef"			"318"
			"ypos_lodef"			"318"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord8Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord8label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-265"
			"xpos_lodef"			"c-265"
			"ypos"			"284"
			"ypos_hidef"			"330"
			"ypos_lodef"			"330"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord8Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord8value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c-155"
			"xpos_lodef"			"c-155"
			"ypos"			"284"
			"ypos_hidef"			"330"
			"ypos_lodef"			"330"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord9Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord9Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord9label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-25"
			"xpos_lodef"			"c-25"
			"ypos"			"294"
			"ypos_hidef"			"246"
			"ypos_lodef"			"246"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord9Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord9Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord9value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c+148"
			"xpos_lodef"			"c+148"
			"ypos"			"294"
			"ypos_hidef"			"246"
			"ypos_lodef"			"246"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord10Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord10Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord10label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-25"
			"xpos_lodef"			"c-25"
			"ypos"			"304"
			"ypos_hidef"			"258"
			"ypos_lodef"			"258"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord10Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord10Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord10value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c+160"
			"xpos_lodef"			"c+160"
			"ypos"			"304"
			"ypos_hidef"			"258"
			"ypos_lodef"			"258"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord11Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord11Label"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord11label%"
			"textAlignment"		"west"
			"xpos"			"c-275"
			"xpos_hidef"			"c-25"
			"xpos_lodef"			"c-25"
			"ypos"			"314"
			"ypos_hidef"			"270"
			"ypos_lodef"			"270"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord11Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord11Value"
			"font"			"ScoreboardVerySmall"
			"font_hidef"	"Default"
			"labelText"		"%classrecord11value%"
			"textAlignment"		"west"
			"xpos"			"c-193"
			"xpos_hidef"			"c+160"
			"xpos_lodef"			"c+160"
			"ypos"			"314"
			"ypos_hidef"			"270"
			"ypos_lodef"			"270"
			"zpos"			"5"
			"wide"			"200"
			"wide_hidef"			"220"
			"wide_lodef"			"220"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
		}
	}
	"ResetStatsButton" [$WIN32]
	{
		"ControlName"		"Button"
		"fieldName"		"ResetStatsButton"
		"xpos"			"c130"
		"ypos"			"270"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_ResetStats"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"resetstatsbutton"
	}
	"CloseButton" [$WIN32]
	{
		"ControlName"		"Button"
		"fieldName"		"CloseButton"
		"xpos"			"r190"
		"ypos"			"r50"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_Close"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"vguicancel"
	}
	"Footer" [$X360]
	{
		"ControlName"		"CTFFooter"
		"fieldName"			"Footer"
		"bgcolor"			"TanDarker"
		"paintbackground"	"1"
		"tall"				"100"
		"tall_lodef"				"60"
		"center"			"1"
		"buttonoffsety"		"20"
		"buttonoffsety_lodef"		"5"
		"button_separator"	"10"
		"button_separator_lodef"	"2"
		"fonttext"			"MatchmakingDialogMenuLarge"
		"fonttext_lodef"			"MatchmakingDialogMenuSmall"
		"buttongap"			"50"
		"textadjust"		"3"
		"textadjust_lodef"		"0"
		"zpos"				"6"
		"fgcolor"			"HudOffWhite" 	
		
		"button"
		{
			"name"		"back"
			"text"		"#GameUI_Back"
			"icon"		"#GameUI_Icons_B_BUTTON"	
		}
		
		"button"
		{
			"name"		"nexttip"
			"text"		"#TF_NextTip_360"
			"icon"		"#GameUI_Icons_A_BUTTON"	
		}
	}		
	"TitleBanner" [$X360]
	{
		"ControlName"	"ImagePanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"128"
		"image"			"menu_header"
		"visible_lodef"	"0"
		"enabled_lodef"	"0"
	}
}
