"Resource\UI\TFContributorsDialog.res"
{
	"TFContribsDialog"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"TFContribsDialog"
		"xpos"		"c-250"
		"ypos"		"90"
		"wide"		"500"
		"tall"		"350"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"bgcolor_override"		"46 43 42 255"
		"paintbackgroundtype"	"2"
		"settitlebarvisible"	""
		"paintborder"			"1"
		"paintbackground"		"0"
		"border"				"GrayDialogBorder"
		"contribs_spacing" 			"20"
		"contribs_init_y_pos"			"50"
		"button_kv"
		{
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"50"
			"tall"			"50"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"border"		"AdvRoundedButtonDefault"
			
			"Username"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"Username"
				"font"			"HudFontSmall"
				"labelText"		"Username"
				"textAlignment"	"east"
				"xpos"			"65"
				"ypos"			"2"
				"zpos"			"2"
				"wide"			"500"
				"tall"			"30"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"TanLight"
				"wrap"			"1"
			}
			
			"Description"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"Description"
				"font"			"HudFontSmallBold"
				"labelText"		"Description"
				"textAlignment"	"east"
				"xpos"			"65"
				"ypos"			"20"
				"zpos"			"2"
				"wide"			"500"
				"tall"			"30"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"TanLight"
				"wrap"			"1"
			}
			
			"AvatarImage"
			{
				"ControlName"	"CAvatarImagePanel"
				"fieldName"		"AvatarImage"
				"xpos"			"15"
				"ypos"			"5"
				"zpos"			"0"
				"wide"			"40"
				"tall"			"40"
				"visible"		"1"
				"enabled"		"1"
				"image"			"error"
				"scaleImage"	"1"	
			}
		}
		"header_kv"
		{
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"0"
			"tall"			"50"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			
			"HeaderText"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"HeaderText"
				"font"			"HudFontSmallBold"
				"labelText"		"HeaderText"
				"textAlignment"	"center"
				"xpos"			"c-342"
				"ypos"			"10"
				"zpos"			"2"
				"wide"			"300"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"wrap"			"0"
			}
		
			"Line"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"Line"
				"xpos"			"0"
				"ypos"			"40"
				"zpos"			"-5-"
				"wide"			"f0"
				"tall"			"10"
				"visible"		"1"
				"enabled"		"1"
				"image"			"loadout_solid_line"
				"scaleImage"	"1"
			}
		}
		
		"tester_kv"
		{
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"50"
			"tall"			"25"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"border"		"AdvRoundedButtonDefault"
			
			"Username"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"Username"
				"font"			"HudFontSmall"
				"labelText"		"Username"
				"textAlignment"	"east"
				"xpos"			"35"
				"ypos"			"0"
				"zpos"			"2"
				"wide"			"500"
				"tall"			"25"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"TanLight"
				"wrap"			"1"
			}
			
			"AvatarImage"
			{
				"ControlName"	"CAvatarImagePanel"
				"fieldName"		"AvatarImage"
				"xpos"			"10"
				"ypos"			"4"
				"zpos"			"0"
				"wide"			"18"
				"tall"			"18"
				"visible"		"1"
				"enabled"		"1"
				"image"			"error"
				"scaleImage"	"1"	
			}
		}
		
		"dev_nosteam_kv"
		{
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"50"
			"tall"			"50"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"border"		"AdvRoundedButtonDefault"
			
			"Username"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"Username"
				"font"			"HudFontSmall"
				"labelText"		"Username"
				"textAlignment"	"east"
				"xpos"			"65"
				"ypos"			"2"
				"zpos"			"2"
				"wide"			"500"
				"tall"			"30"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"TanLight"
				"wrap"			"1"
			}
			
			"Description"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"Description"
				"font"			"HudFontSmallBold"
				"labelText"		"Description"
				"textAlignment"	"east"
				"xpos"			"65"
				"ypos"			"20"
				"zpos"			"2"
				"wide"			"500"
				"tall"			"30"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"TanLight"
				"wrap"			"1"
			}
			
			"AvatarImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"AvatarImage"
				"xpos"			"15"
				"ypos"			"5"
				"zpos"			"0"
				"wide"			"40"
				"tall"			"40"
				"visible"		"1"
				"enabled"		"1"
				"image"			"error"
				"scaleImage"	"1"	
			}
		}
	}
	"TitleLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TitleLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"CREDITS"
		"textAlignment"	"center"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"500"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	
	"FooterLine"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"FooterLine"
		"xpos"			"0"
		"ypos"			"300"
		"zpos"			"-5-"
		"wide"			"f0"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"image"			"loadout_solid_line"
		"scaleImage"	"1"
	}
	
	"HeaderLine"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HeaderLine"
		"xpos"			"0"
		"ypos"			"40"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"image"			"loadout_solid_line"
		"scaleImage"	"1"
	}
	
	"CancelButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"			"200"
		"ypos"			"312"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Close"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"Close"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"PanelListPanel"
	{
		"ControlName"		"CPanelListPanel"
		"fieldName"		"PanelListPanel"
		"xpos"		"10"
		"ypos"		"40"
		"wide"		"480"
		"tall"		"260"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"bgcolor_override"	"0 0 0 0"
	}
}
